language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t aalandril/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aalandril/docker-react npm run test