version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - /app/node_modules
            - .:/app:consistent
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        volumes:
            - /app/node_modules
            - .:/app:consistent
        command: ["npm", "run", "test"]